In [ ]:
#Samurai Engeneer

Kadai_005_017

##kadai_005

In [ ]:
##kadai_005
# 台形の寸法（cm）
top = 10
bottom = 20
height = 5

# 面積の計算
area = (top + bottom) * height / 2

# 結果の出力（単位cm²）
print(f"{area}cm²")


75.0cm²


In [ ]:
top = 20
bottom = 20
height = 30
area = top * height
print(f"{area}cm²")

600cm²


##kadai_Continue

In [ ]:
##kadai_Continue
# インデントなし
for i in range(1, 11):
    # インデント4 ループ変数iの値が奇数（2で割った余りが1）の時に、値を出力せずcontinue文で次のループに進む
    if i % 2 == 1:
      # インデント2
      continue

    print (i)

2
4
6
8
10


TOTO?みたいな文

In [ ]:
#ランダムな整数を利用するため、記述が必要です。
import random
# 変数numに0~10までのランダムな整数を代入する
num = random.randint(0, 10)
# 変数numの値が0以外である間、変数numの値を出力し続ける
while num != 0:
  num = random.randint(0, 10)
  print(num)

3
10
6
10
8
8
0


##kadai_（For繰り返し処理）

In [ ]:
# For文ループで9行表示
array = ["水","金","地","火","木","土","天","海","冥"]
for planet in array:
    print(planet)

水
金
地
火
木
土
天
海
冥


kadai_（While繰り返し処理）

In [ ]:
# whileループで9行表示
array = ["水","金","地","火","木","土","天","海","冥"]

i = 0
while i < len(array):
    print(array[i])
    i += 1

水
金
地
火
木
土
天
海
冥


関数の呼び出し方

In [ ]:
# 朝のあいさつを出力する関数を作成する
def say_good_morning():
    print("おはようございます！")
    print("昨日はよく眠れましたか？")
    print("今日も一日頑張りましょう！")

# 夜のあいさつを出力する関数を作成する
def say_good_evening():
    print("こんばんは！")
    print("今日も一日お疲れさまでした。")

# 朝のあいさつを出力する関数を呼び出す
say_good_morning()

# 夜のあいさつを出力する関数を呼び出す
say_good_evening()


おはようございます！
昨日はよく眠れましたか？
今日も一日頑張りましょう！
こんばんは！
今日も一日お疲れさまでした。


kadai_時間で挨拶を変える

In [ ]:
from datetime import datetime

def say_greeting_by_time():
    hour = datetime.now().hour

    if hour == 8:
        print("おはようございます")
    elif hour == 12:
        print("こんにちは")
    elif hour == 17:
        print("こんばんは")

# 関数を呼び出す
say_greeting_by_time()

時間で挨拶を変える（TEST)

In [ ]:
def say_greeting_by_time(hour):
    if hour == 8:
        print("おはようございます")
    elif hour == 12:
        print("こんにちは")
    elif hour == 17:
        print("こんばんは")

# テスト用
say_greeting_by_time(12)

こんにちは


##kadai_価格

In [ ]:
# 与えられた引数$priceに送料を加算し、その値を出力する関数を定義する
def calculate_total(price):
    # 与えられた引数priceに送料を加算し、変数totalに代入する
    total = price + 500

    # 変数totalの値を出力する
    print(f"{total}円")

# 関数を呼び出し、引数として購入金額を渡す
calculate_total(1200)

1700円


##kadai_013

In [ ]:
# 引数$priceに送料を加算し、その値を出力する関数を定義する
def calculate_total(price):
    # 与えられた引数priceに消費税１０％を加算し、変数totalに代入して、整数にする
    total = price * 1.1

    # 変数totalの値を出力する
    print(f"{total}円")

# 関数を呼び出し、引数として購入金額を渡す
calculate_total(110)

121.00000000000001円


In [ ]:
# 引数$priceに送料と税金１０％を加算し、その値を出力する関数を定義する
def calculate_total(price, tax_percent):
    tax_rate = tax_percent / 100
    total = price * (1 + tax_rate)
    return total

# 関数を呼び出し、引数として購入金額を表示
result = calculate_total(110, 10)
print(result)

121.00000000000001


##侍太郎のエラーバージョン

In [ ]:
＃侍太郎のエラーバージョン
def show_user_name():
    # ローカル変数を定義する
    user_name = "侍太郎"

    # ローカルスコープの範囲内でローカル変数を使う
    print(user_name)

show_user_name()

# ローカルスコープの範囲外でローカル変数を使う（エラーが発生する）
print(user_name)



SyntaxError: invalid character '＃' (U+FF03) (ipython-input-2454572221.py, line 1)

侍太郎の正解バージョン

In [ ]:
def show_user_name():
    # ローカル変数を定義する
    user_name = "侍太郎"
    # ローカルスコープの範囲内でローカル変数を使う
    print(user_name)

show_user_name()

侍太郎


In [ ]:
# グローバル変数を定義する
user_name = "侍花子"

def show_user_name():
    # ローカル変数を定義する
    user_name = "侍太郎"

    # ローカルスコープの範囲内でローカル変数を使う
    print(user_name)

show_user_name()

# グローバルスコープの範囲内でグローバル変数を使う
print(user_name)

侍太郎
侍花子


In [ ]:
# グローバル変数を定義する
user_name = "侍花子"

def show_user_name():
    # ローカル変数を定義する
    user_name = "侍太郎"
    # user_name = "侍太郎"

    # ローカルスコープの範囲内でローカル変数を使う
    # グローバルスコープの範囲外でグローバル変数を使う（エラーが発生しない）
    print(user_name)

show_user_name()

# グローバルスコープの範囲内でグローバル変数を使う
print(user_name)

侍太郎
侍花子


##kadai_014

kadai_014　不正解バージョン

In [ ]:
price1 = 100
price2 = 200

def total():
  tax = 1.1
    return price1 + price2

print (total() * tax)

IndentationError: unexpected indent (ipython-input-2571711009.py, line 6)

kadai_014

In [ ]:
price1 = 100
price2 = 200
tax = 1.1

def total():
    return price1 + price2

print(round(total() * tax))

330


In [ ]:
price1 = 100
price2 = 200
tax = 1.1

def total():
    return price1 + price2

print (round(total() * tax))

330


kadai_014_2

In [ ]:
def total(price1, price2, tax=1.1):
    return (price1 + price2) * tax

print(round(total(100, 200)))

330


##kadai_クラス

In [ ]:
class Product:
    def __init__(self):
        # 属性を定義する
        self.name = ""

shampoo = Product()

# 属性にアクセスし、値を代入する
shampoo.name = "シャンプー"

# 属性にアクセスし、値を出力する
print(shampoo.name)

シャンプー


In [ ]:
class Product:
    def __init__(self):
        # 属性を定義する
        self.name = ""

goods = Product()

# 属性にアクセスし、値を代入する
goods.name = "流行りの逸品"

# 属性にアクセスし、値を出力する
print(goods.name)

流行りの逸品


クラス勉強　イベント開催：インデント勉強

In [ ]:
#インデントなし
from datetime import datetime
class Event:
  #インデント2
  def __init__(self, name: str, date: str, location: str):
      #インデント4
      """コンストラクタ
      :param name: イベント名
      :param date: 開催日('YYYY-MM-DD')
      :param location: 開催場所
      """

      self.name = name
      self.date = datetime.strptime(date, "%Y-%m-%d")
      self.location = location

  #インデント2 開催日までの日数を出力
  def days_until_event(self) -> int:
      #インデント4 開催日までの日数を出力
      """開催日までの日数を返す"""
      today = datetime.today()
      return (self.date - today).days

#===== ここからが実行される =====
#インデントなし
event = Event("プログラミング初心者向けセミナー", "2026-02-15", "東京国際フォーラム")

#インデントなし
#各属性の値を出力
print(f"イベント名: {event.name}")
print(f"開催日: {event.date.strftime('%Y-%m-%d')}")
print(f"開催場所: {event.location}")
print(f"開催日までの日数: {event.days_until_event()}日")


イベント名: プログラミング初心者向けセミナー
開催日: 2026-02-15
開催場所: 東京国際フォーラム
開催日までの日数: 62日


##kadai_イベント開催：正解パターン

In [ ]:
from datetime import datetime

class Event:
    def __init__(self, name: str, date: str, location: str):
        """コンストラクタ
        :param name: イベント名
        :param date: 開催日('YYYY-MM-DD')
        :param location: 開催場所
        """
        self.name = name
        self.date = datetime.strptime(date, "%Y-%m-%d")
        self.location = location

# 開催日までの計算を定義
    def days_until_event(self) -> int:
        """開催日までの日数を返す"""
        today = datetime.today()
        return (self.date - today).days


# ===== ここからが実行される =====
event = Event(
    "プログラミング初心者向けセミナー",
    "2026-02-15",
    "東京国際フォーラム"
)
#各属性の値を出力
print(f"イベント名: {event.name}")
print(f"開催日: {event.date.strftime('%Y-%m-%d')}")
print(f"開催場所: {event.location}")
#開催日までの日数を出力
print(f"開催日までの日数: {event.days_until_event()}日")


イベント名: プログラミング初心者向けセミナー
開催日: 2026-02-15
開催場所: 東京国際フォーラム
開催日までの日数: 62日


##kadai_015

In [ ]:
class Human:
    def __init__(self, name: str, age: int):
        self.name = name
        self.age = age

    def printinfo(self):
        print(f"名前: {self.name}")
        print(f"年齢: {self.age}")


# Humanクラスのインスタンスを作成して変数に代入
human = Human("uni", 8)

# メソッドを呼び出す
human.printinfo()

名前: uni
年齢: 8


##kadai_017

In [ ]:
#名前(name)と年齢(age)の属性を持つHumanクラスを作成
#Humanクラスは、以下の条件で標準出力(print)するcheck_adultメソッドを追加
#ageが20以上の場合に大人、そうでない場合に大人でない
#Humanクラスのインスタンスを複数生成してリストに追加し、check_adultメソッドを呼び出し
#リスト・ディクショナリ、条件分岐、繰り返し処理、関数、変数のスコープ、クラスで課題の仕様通りのプログラム作成

class Human:
    def __init__(self, name: str, age: int):
        """Humanクラスのコンストラクタ
        :param name:
        :param age: 年齢
        """
        self.name = name
        self.age = age

    def check_adult(self):
        """大人かどうかを判定して出力する"""
        if self.age >= 20:
            print(f"{self.name}は大人です。")
        else:
            print(f"{self.name}は大人ではありません。")


# ===== ここから実行部分 =====
# Humanクラスのインスタンスを複数生成してリストに追加
humans = [
    Human("ぶり", 30),
    Human("うの", 18),
    Human("うに", 20),
    Human("らく", 15)
]

# リストの要素数分だけcheck_adultメソッドを呼び出す
for human in humans:
    human.check_adult()

ぶりは大人です。
うのは大人ではありません。
うには大人です。
らくは大人ではありません。


再現 kadai_017

In [ ]:
class Human:
  def __init__(self, name: str, age: int):
      """Humanのコンストラクタ
      :param name:
      :param age: 年齢
      """

      self.name = name
      self.age = age

  def check_adult(self):
    """大人か判定"""
    if self.age >= 20:
      print(f"{self.name}は大人です。")
    else:
      print(f"{self.name}は大人ではありません。")

humans = [
    Human("ぶり", 20),
    Human("らく", 19),
      ]

for human in humans:
    human.check_adult()



ぶりは大人です。
らくは大人ではありません。


再現 kadai_017　の　省略版

In [ ]:
class Human:
  def __init__(self, name: str, age: int):
      self.name = name
      self.age = age

  def check_adult(self):
    if self.age >= 20:
      print(f"{self.name}は大人です。")
    else:
      print(f"{self.name}は大人ではありません。")

humans = [
    Human("ぶり", 20),
    Human("らく", 19),
      ]

for human in humans:
    human.check_adult()

ぶりは大人です。
らくは大人ではありません。


##kadai_時刻

In [ ]:
# timeモジュールをインポート
import time

# 現在時刻をUNIXタイムスタンプで取得
print(time.time())

1765772283.1564093


In [ ]:
# datetimeモジュールをインポート
import datetime

# 現在の日時を取得する
now = datetime.datetime.now()

# 指定した日付を取得する
date = datetime.datetime.strptime("2015-03-19", "%Y-%m-%d")

# 指定した日時を取得する
date_time = datetime.datetime.strptime("2015-03-19 12:15:30", "%Y-%m-%d %H:%M:%S")

print now()

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (ipython-input-4244516707.py, line 13)

NumPy

In [ ]:
import numpy as np
narray = np.array([1, 2, 3])
narray

array([1, 2, 3])

In [ ]:
narray.size

3

In [ ]:
type(narray)

numpy.ndarray

In [ ]:
nones = np.ones(10)
nones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
type(nones)

numpy.ndarray

In [ ]:
multi_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
multi_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.random.rand()

0.5486274457587266

In [ ]:
np.random.rand(3)

array([0.6128381 , 0.28888586, 0.65632565])

In [ ]:
np.random.rand(3, 3)

array([[0.03058337, 0.25027648, 0.86100893],
       [0.50653282, 0.00357496, 0.68400646],
       [0.50848739, 0.11840904, 0.85457818]])

In [ ]:
np.random.randint(1, 10)

6

In [ ]:
np.random.randint(1, 10, (5,))

array([5, 1, 6, 2, 8])

In [ ]:
random_multi_array = np.random.randint(1, 10, (5,5))
random_multi_array

array([[4, 9, 6, 7, 6],
       [1, 5, 2, 9, 9],
       [5, 9, 6, 9, 4],
       [1, 4, 7, 6, 6],
       [8, 4, 9, 4, 7]])

In [ ]:
random_multi_array.max()

np.int64(9)

In [ ]:
random_multi_array.min()

np.int64(1)

In [ ]:
random_array = np.random.randint(1, 10, (10,))
random_array

array([5, 2, 7, 1, 4, 4, 7, 7, 7, 5])

In [ ]:
random_array[0:3]

array([5, 2, 7])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
three = np.ones(3)
three

array([1., 1., 1.])

In [ ]:
three + 3

array([4., 4., 4.])

In [ ]:
three + [1, 0 , 1]

array([2., 1., 2.])

In [ ]:
six_reshape = np.arange(6).reshape(2, 3)
six_reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
six_reshape + 1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
six_reshape + np.array([[1, 0 ,2], [1, 0, 2]])

array([[1, 1, 4],
       [4, 4, 7]])

In [ ]:
five_full = np.full(5, 5)
five_full

array([5, 5, 5, 5, 5])

In [ ]:
five_full - 2

array([3, 3, 3, 3, 3])

In [ ]:
five_full - np.array([1, 2, 3 ,4 ,5])

array([4, 3, 2, 1, 0])

In [ ]:
ten = np.arange(10)
ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
ten * np.array([1, 2, 2, 2, 3, 3, 3, 4, 4, 5])

array([ 0,  2,  4,  6, 12, 15, 18, 28, 32, 45])

In [ ]:
div_six = np.arange(6)
div_six

array([0, 1, 2, 3, 4, 5])

In [ ]:
div_six / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
A = np.array([[4, 7, 2], [1, 2, 1]])
B = np.array([[2, 2, 2], [4, 5, 2], [9, 2, 1]])
np.dot(A, B)

array([[54, 47, 24],
       [19, 14,  7]])

In [ ]:
# 逆行列を求めるinvメソッドをインポート
from numpy.linalg import inv
A = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 1]])
ainv = inv(A)
ainv

array([[ 1., -1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
np.dot(A, ainv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.array([1, 2, 3])
np.sum(a)

np.int64(6)

In [ ]:
a = np.array([[14, 8, 11, 10], [7, 9, 10, 11], [10, 15, 5, 10]])
np.sum(a)

np.int64(120)

In [ ]:
np.sum(a, axis=0)

array([31, 32, 26, 31])

In [ ]:
np.sum(a, axis=1)

array([43, 37, 40])

In [ ]:
a = np.array([1,2,3,4])
np.median(a)

np.float64(2.5)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
np.std(a)

np.float64(1.4142135623730951)

In [ ]:
rom PIL import Image
2import numpy as np
3
4# 画像を読み込む
5im = Image.open("camera.jpg")
6im = im.resize((im.width //2, im.height //2)) # 元の画像はデカいので縮小
7im

SyntaxError: invalid decimal literal (ipython-input-4247482120.py, line 2)

In [ ]:
# PIL形式からNumPy形式に変換
im_np = np.asarray(im)
im_np

NameError: name 'im' is not defined

In [ ]:
255 - im_np

NameError: name 'im_np' is not defined

In [ ]:
# ネガティブ画像へ変換する（ブロードキャストが機能する）
negative_im_np = 255 - im_np
negative_im = Image.fromarray(negative_im_np)
negative_im

NameError: name 'im_np' is not defined

##kadai_003

In [ ]:
## kadai_003
# Step1. NumPyをインポート
import numpy as np

# Step2. 行列A・Bを多次元配列として定義
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

B = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

# Step3. 行列の積を計算
C = np.dot(A, B)

# Step4. 計算結果を表示
print("行列の積の結果:")
print(C)

# Step5. 行列要素の最大値を求めて表示
max_value = np.max(C)
print("行列の最大値:", max_value)


行列の積の結果:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の最大値: 47
